export enum EventType {
  IGNITION_ON = 'IGNITION_ON',
  IGNITION_OFF = 'IGNITION_OFF',
  GEOFENCE_ENTER = 'GEOFENCE_ENTER',
  GEOFENCE_EXIT = 'GEOFENCE_EXIT',
  SPEED_ALERT = 'SPEED_ALERT',
  PANIC_BUTTON = 'PANIC_BUTTON',
  LOW_BATTERY = 'LOW_BATTERY',
  NO_MOVEMENT = 'NO_MOVEMENT',
  HARD_BRAKE = 'HARD_BRAKE',
  HARD_ACCELERATION = 'HARD_ACCELERATION',
}

